{% set version = "1.3.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-datavisualizations
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/DataVisualizations_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/DataVisualizations/DataVisualizations_{{ version }}.tar.gz
  sha256: 42585fcb2ad47e072b8c6264b8c540e9be28ff10b06fa7101f720ad68c1400d4

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ggplot2
    - r-pracma
    - r-rcpp >=0.12.12
    - r-rcppparallel >=5.1.4
    - r-reshape2
    - r-sp
    - libblas
  run:
    - r-base
    - r-ggplot2
    - r-pracma
    - r-rcpp >=0.12.12
    - r-rcppparallel >=5.1.4
    - r-reshape2
    - r-sp

test:
  commands:
    - $R -e "library('DataVisualizations')"           # [not win]
    - "\"%R%\" -e \"library('DataVisualizations')\""  # [win]

about:
  home: http://www.deepbionics.org
  license: GPL-3.0-only
  summary: "Gives access to data visualisation methods that are relevant from the data scientist's point of view. The flagship idea of 'DataVisualizations' is the mirrored density plot (MD-plot) for either classified or non-classified multivariate data published in Thrun, M.C. et al.: \"Analyzing the Fine Structure of Distributions\"\
    \ (2020), PLoS ONE, <DOI:10.1371/journal.pone.0238835>. The MD-plot outperforms the box-and-whisker diagram (box plot), violin plot and bean plot and geom_violin plot of ggplot2. Furthermore, a collection of various visualization methods for univariate data is provided. In the case of exploratory data analysis, 'DataVisualizations'
    makes it possible to inspect the distribution of each feature of a dataset visually through a combination of four methods. One of these methods is the Pareto density estimation (PDE) of the probability density function (pdf). Additionally, visualizations of the distribution of distances using PDE, the scatter-density
    plot using PDE for two variables as well as the Shepard density plot and the Bland-Altman plot are presented here. Pertaining to classified high-dimensional data, a number of visualizations are described, such as f.ex. the heat map and silhouette plot. A political map of the world or Germany can be visualized with the
    additional information defined by a classification of countries or regions. By extending the political map further, an uncomplicated function for a Choropleth map can be used which is useful for measurements across a geographic area. For categorical features, the Pie charts, slope charts and fan plots, improved by the
    ABC analysis, become usable. More detailed explanations are found in the book by Thrun, M.C.: \"Projection-Based Clustering through Self-Organization and Swarm Intelligence\" (2018) <DOI:10.1007/978-3-658-20540-9>."

  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
